#port 수정
server:
  port: 9090

#DB Connection
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: planner
    password: planner
   
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
#    database: oracle
#    database-platform: org.hibernate.dialect.Oracle10gDialect
    defer-datasource-initialization: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5242880000
      max-request-size: 5242880000

#  mvc:
#    static-path-pattern: /static/**
logging.level:
  org:
    hibernate:
      SQL: debug
      type: trace

    
    
    
    
    
    
    

    
    
    
    
    
    
    
    